import globals from 'globals'
import js from '@eslint/js'

export default {
	languageOptions: {
		globals: {
			...globals.browser,
		},
	},
	rules: {
		...js.configs.recommended.rules,
		'array-callback-return': 2,
		'no-await-in-loop': 2,
		'no-constructor-return': 2,
		'no-duplicate-imports': 2,
		'no-inner-declarations': 2,
		'no-promise-executor-return': 2,
		'prefer-rest-params': 2,
		'no-self-compare': 2,
		'prefer-template': 2,
		'sort-imports': 2,
		'symbol-description': 2,
		'no-template-curly-in-string': 2,
		'no-unmodified-loop-condition': 2,
		'no-unreachable-loop': 2,
		'no-use-before-define': 2,
		'no-useless-assignment': 2,
		'class-methods-use-this': 2,
		'default-case': 2,
		'default-case-last': 2,
		'default-param-last': 2,
		'dot-notation': 2,
		eqeqeq: 2,
		'func-name-matching': 2,
		'grouped-accessor-pairs': 2,
		'init-declarations': 2,
		'new-cap': 2,
		'no-console': 1,
		'no-empty-function': 2,
		'no-eq-null': 2,
		'no-eval': 1,
		'no-implied-eval': 2,
		'no-invalid-this': 2,
		'no-lone-blocks': 2,
		'no-loop-func': 2,
		'no-magic-numbers': 2,
		'no-multi-assign': 2,
		'no-multi-str': 2,
		'no-new': 2,
		'no-new-func': 2,
		'no-param-reassign': 2,
		'no-return-assign': 2,
		'no-shadow': 2,
		'no-unneeded-ternary': 2,
		'no-unused-expressions': 2,
		'no-useless-call': 2,
		'no-useless-computed-key': 2,
		'no-useless-concat': 2,
		'no-useless-constructor': 2,
		'no-useless-rename': 2,
		'no-useless-return': 2,
		'no-var': 2,
		'object-shorthand': 2,
		'operator-assignment': 2,
		'prefer-arrow-callback': 2,
		'prefer-const': 2,
		'prefer-destructuring': 2,
	},
}
